aws:
  access_key_id:      mykey
  secret_access_key:  mysecret
  region:             us-east-1 # or <%= ENV['AWS_REGION'] %>
  receive_message:
    attributes:
      - receive_count
      - sent_at
concurrency: 25,  # The number of allocated threads to process messages. Default 25
delay: 25,        # The delay in seconds to pause a queue when it's empty. Default 0
queues:
  - [myinstance-tosolve-priority, 2]
  - [myinstance-tosolve, 1]
